<?php

namespace TvShowManagerBundle\Repository;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all TvShow with his episodes
     * @return array
     */
    public function myFindAll(){
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
            ->join('t.episodes', 'e')
            ->addSelect('e');
        return $qb->getQuery()->getResult();
    }

    /**
     * Get one TvShow by id and his episodes
     * @param $id int
     * @return mixed
     */
    public function myFindOneById($id){
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
            ->where('t.id = :id')
            ->join('t.episodes', 'e')
            ->addSelect('e')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
