<?php

namespace TvShowManagerBundle\Repository;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t', 'e as episode')
            ->join('t.episodes', 'e');
        return $qb->getQuery()->getResult();

    }

    public function myFindOneById($id)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
            ->where('t.id = :id')
            ->join('t.episodes', 'e')
            ->addSelect('e')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
