tv_show_manager_homepage:
    path:     /
    defaults: { _controller: TvShowManagerBundle:Default:index }

tvShow_route:
    prefix: /tvshow
    resource: '@TvShowManagerBundle/Resources/config/doctrine/routing/tvShow.yml'
