TvShowManagerBundle\Entity\TvShow:
    type: entity
    table: null
    repositoryClass: TvShowManagerBundle\Repository\TvShowRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        url:
            type: string
            length: 255
        year:
            type: integer
    lifecycleCallbacks: {  }

    oneToMany:
        episodes:
            targetEntity: TvShowManagerBundle\Entity\Episode
            mappedBy: tvShow
# => initialize the collection in
# the __construct() method of the entity